---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vladivostokbot-deployment
  labels:
    app: vladivostokbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vladivostokbot
  template:
    metadata:
      labels:
        app: vladivostokbot
    spec:
      containers:
        - name: vladivostokbot
          image: kuskoman/vladivostokbot:latest
          imagePullPolicy: "IfNotPresent"
          envFrom:
            - configMapRef:
                name: vladivostokbot-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vladivostokbot-config
  labels:
    app: vladivostokbot
data:
  DISCORD_TOKEN: YOUR_DISCORD_TOKEN
---

